import { useEffect, useState } from 'react';
import { suggestedAvatar, suggestedDisplayName } from '../../domain/journeyProfile';

const avatars = ['🦊', '🐰', '🐧', '🐱', '🐶', '🦉', '🐻', '🐯', '🐸', '🐼', '🌟', '☁️', '🌱', '🚀', '🎒', '📚', '🧭', '💡', '🎨', '🛠️'];

export function IdentityStep({ onContinue }: { onContinue: () => void }) {
  const [legalName, setLegalName] = useState('');
  const [displayName, setDisplayName] = useState(() => suggestedDisplayName());
  const [avatar, setAvatar] = useState('🦊');
  const [manual, setManual] = useState(false);
  const [picker, setPicker] = useState(false);
  const [settled, setSettled] = useState(false);
  useEffect(() => { if (displayName || manual) return; const timer = window.setInterval(() => setAvatar((current) => avatars[(avatars.indexOf(current) + 1) % avatars.length]), 320); return () => clearInterval(timer); }, [displayName, manual]);
  useEffect(() => { if (!displayName.trim() || manual) return; setSettled(false); const timer = window.setTimeout(() => { setAvatar(suggestedAvatar(displayName)); setSettled(true); }, 500); return () => clearTimeout(timer); }, [displayName, manual]);
  const valid = displayName.trim().length >= 2 && displayName.trim().length <= 16;
  return <section className="journey-card max-w-3xl mx-auto rounded-[2rem] p-6 md:p-8 text-[#202124]"><p className="text-sm font-bold text-[#1a73e8]">여정 준비 3 / 8</p><h1 className="text-3xl font-black mt-1">이름과 캐릭터</h1><div className="grid md:grid-cols-2 gap-6 mt-7"><div className="space-y-5"><div><h2 className="font-black">운영 확인을 위한 이름</h2><p className="text-sm text-[#5f6368] mt-1">이 이름은 본인과 운영자만 확인할 수 있어요. 랭킹이나 공개 공간에는 표시되지 않아요.</p><input value={legalName} onChange={(event) => setLegalName(event.target.value)} className="w-full mt-3 rounded-xl border border-[#dadce0] px-4 py-3" placeholder="실명 또는 운영 확인 이름" /></div><div><h2 className="font-black">여정에서 사용할 이름</h2><p className="text-sm text-[#5f6368] mt-1">캘린더, 랭킹과 함께 배우는 공간에는 이 이름이 보여요.</p><div className="flex gap-2 mt-3"><input value={displayName} onChange={(event) => { setManual(false); setDisplayName(event.target.value); }} className="min-w-0 flex-1 rounded-xl border border-[#dadce0] px-4 py-3" /><button onClick={() => { setManual(false); setDisplayName(suggestedDisplayName()); }} className="rounded-xl bg-[#e8f0fe] px-3 text-sm font-bold text-[#1967d2]">다른 이름 추천</button></div>{!valid && <p className="text-xs text-[#d93025] mt-2">공개 이름은 공백이 아닌 2~16자로 입력해주세요.</p>}</div></div><aside className="rounded-2xl bg-[#f8f9fa] p-6 text-center relative"><p className="text-sm font-bold text-[#5f6368]">다른 사람에게는 이렇게 보여요</p><button onClick={() => setPicker(!picker)} className="text-7xl mt-4" aria-label="캐릭터 선택">{avatar}</button><h2 className="font-black text-xl mt-3">{displayName.trim() || '여정 이름을 기다리는 중'}</h2><p className="text-sm text-[#5f6368]">새내기 구글러 {settled && '· 추천 완료'}</p><button onClick={() => { setManual(false); setAvatar(suggestedAvatar(`${displayName}-${Date.now()}`)); }} className="mt-4 rounded-xl border border-[#dadce0] px-4 py-2 text-sm font-bold">다른 캐릭터 추천</button>{picker && <div className="absolute inset-x-4 top-20 rounded-2xl bg-white p-4 shadow-xl border border-[#dadce0]"><button onClick={() => setPicker(false)} className="float-right text-sm">닫기</button><div className="grid grid-cols-5 gap-2 clear-both pt-3">{avatars.map((item) => <button key={item} onClick={() => { setAvatar(item); setManual(true); setPicker(false); }} className="rounded-xl p-2 text-2xl hover:bg-[#e8f0fe]">{item}</button>)}</div></div>}</aside></div><button disabled={!valid} onClick={onContinue} className="mt-8 rounded-xl bg-[#1a73e8] px-6 py-3 font-bold text-white disabled:bg-[#dadce0]">이 모습으로 계속하기</button></section>;
}
