import { useEffect, useRef, useState } from 'react';
import LegacyGooglerApp from '../../legacy/LegacyGooglerApp';
import { suggestedDisplayName } from '../../domain/journeyProfile';
import { startJourneyBgm, stopJourneyBgm } from '../audio/audioEngine';
import { IdentityStep } from './IdentityStep';

const questions = ['Google 계정을 직접 만들 수 있나요?', '비밀번호를 잊었을 때 복구할 수 있나요?', 'Gmail에서 파일을 첨부해 보냈나요?', 'Drive 폴더와 공유 권한을 설정했나요?', 'Docs·Slides·Sheets 공동 작업을 해봤나요?', 'Classroom 또는 교육 도구를 사용했나요?', '이번 여정의 목표는 무엇인가요?'];
const levels = [{ name: '처음부터 시작하기', text: 'Google 계정 만들기, 로그인, 로그아웃, 비밀번호 찾기부터 차근차근 배워요.', weeks: '8주' }, { name: '기초를 탄탄하게', text: 'Gmail과 Drive의 기본 행동을 익히며 학습 리듬을 만들어요.', weeks: '6주' }, { name: '활용 능력 넓히기', text: '협업 도구와 수업·업무 활용 능력을 넓혀요.', weeks: '5주' }, { name: '심화·시험 준비', text: '인증 시험과 실제 활용을 위한 심화 여정이에요.', weeks: '4주' }];
const tones = [{ name: '차분한 코치', line: '오늘도 한 걸음씩, 충분히 잘하고 있어요.' }, { name: '발랄한 메이트', line: '좋아! 오늘 미션도 같이 깨보자! ✨' }, { name: '도전형 트레이너', line: '준비 완료. 오늘의 기록을 갱신해볼까요?' }];
const messages = ['Google 계정의 첫 문을 열고 있어요.', '당신의 학습 리듬을 살피고 있어요.', '이번 주의 작은 승리를 고르고 있어요.', '복습과 보충일을 균형 있게 배치하고 있어요.', 'Google Educator 여정에 색을 입히고 있어요.', '첫 미션을 조심스럽게 고르고 있어요.'];

export default function JourneyPrototype() {
  const [mode, setMode] = useState<string>('entry');
  const [step, setStep] = useState(0); const [name, setName] = useState(suggestedDisplayName()); const [level, setLevel] = useState(0); const [tone, setTone] = useState(1); const [sound, setSound] = useState(() => localStorage.getItem('journey-sound') !== 'off'); const audio = useRef<AudioContext | null>(null);
  const play = (frequency=440) => { if (!sound || typeof AudioContext === 'undefined') return; if (!audio.current) audio.current = new AudioContext(); const oscillator=audio.current.createOscillator(); const gain=audio.current.createGain(); gain.gain.value=.025; oscillator.frequency.value=frequency; oscillator.connect(gain).connect(audio.current.destination); oscillator.start(); oscillator.stop(audio.current.currentTime+.08); };
  useEffect(()=>localStorage.setItem('journey-sound', sound ? 'on':'off'),[sound]);
  useEffect(()=>{ if (!sound) stopJourneyBgm(); return ()=>stopJourneyBgm(); },[sound]);
  useEffect(()=>{ if(mode!=='loading') return; const id=setTimeout(()=>setMode('planner'), 2400); return()=>clearTimeout(id);},[mode]);
  const journeyStages = ['여정 시작','계정 준비','이름과 캐릭터','수준 진단','출발 단계','학습 리듬','코치 선택','플래너 생성']; const stage = mode==='entry'?1:mode==='return'?2:mode==='new'?3:mode==='diagnostic'?4:mode==='level'?5:mode==='tone'?7:8;
  const shell=(children: React.ReactNode)=><main className="journey-shell min-h-screen px-4 py-6"><div className="max-w-4xl mx-auto"><header className="flex items-center justify-between gap-3 mb-8"><div><p className="text-xs font-bold text-[#5f6368]">여정 준비 {stage} / 8</p><p className="text-sm font-bold text-[#1a73e8]">{journeyStages[stage-1]}</p></div><button onClick={()=>setSound(!sound)} className="rounded-full border border-[#dadce0] bg-white px-4 py-2 text-sm text-[#202124]">{sound?'🔊 사운드':'🔇 음소거'}</button></header><div className="h-1.5 rounded-full bg-[#e8eaed] mb-8 overflow-hidden"><div className="journey-progress h-full transition-all" style={{width:`${stage/8*100}%`}} /></div>{children}</div></main>;
  if(mode==='legacy') return <LegacyGooglerApp />;
  if(mode==='new') return shell(<IdentityStep onContinue={() => { play(); setMode('diagnostic'); }} />);
  if(mode==='entry') return shell(<><p className="text-[#1a73e8] font-bold">Google Educator journey</p><h1 className="journey-title text-5xl font-black mt-8">Be a Googler</h1><p className="text-xl text-[#5f6368] mt-5">배우고, 직접 해보고, 함께 성장하는<br/>구글러의 여정을 시작해보세요.</p><div className="grid md:grid-cols-2 gap-5 mt-12">{[['처음 여정을 시작해요','나에게 맞는 출발점을 찾아볼게요.','🌱','new'],['내 여정을 이어가요','지난 구글러 여정으로 돌아갈게요.','🧭','return']].map(([title,text,icon,target])=><button key={title} onClick={()=>{startJourneyBgm(sound);play(520);setMode(target as typeof mode)}} className="journey-card text-left rounded-[2rem] p-8 hover:scale-[1.02] transition"><span className="text-4xl">{icon}</span><h2 className="text-2xl font-black mt-5">{title}</h2><p className="text-[#5f6368] mt-2">{text}</p></button>)}</div></>);
  if(mode==='return') return shell(<section className="max-w-md mx-auto pt-20"><h1 className="text-3xl font-black">다시 만나 반가워요</h1><p className="text-white/70 mt-2">지난 구글러 여정을 이어가볼까요?</p><input className="w-full mt-8 rounded-2xl p-4 text-[#202124]" placeholder="이메일 또는 아이디" /><input type="password" className="w-full mt-3 rounded-2xl p-4 text-[#202124]" placeholder="비밀번호" /><button onClick={()=>{play();setMode('planner')}} className="w-full mt-5 rounded-2xl bg-[#4285f4] p-4 font-bold">여정 이어가기</button><button onClick={()=>setMode('entry')} className="w-full mt-3 text-white/60">처음으로</button></section>);
  if(mode==='new'||mode==='diagnostic') return shell(<section className="max-w-2xl mx-auto pt-10"><p className="text-[#8ab4f8]">나를 알아가는 중 · {mode==='new'?'1':'2'} / 2</p><div className="h-2 bg-white/15 rounded-full mt-3"><div className="h-full w-1/2 bg-[#4285f4] rounded-full" /></div>{mode==='new'?<><h1 className="text-3xl font-black mt-10">여정에서 사용할 이름은 무엇인가요?</h1><input value={name} onChange={e=>setName(e.target.value)} className="w-full mt-7 rounded-2xl p-4 text-[#202124]" placeholder="예: 지혜로운 구글러" /><button onClick={()=>{play();setMode('diagnostic')}} className="mt-6 rounded-2xl bg-[#4285f4] px-8 py-4 font-bold">출발점 찾기</button></>:<><h1 className="text-3xl font-black mt-10">{questions[step]}</h1><div className="grid gap-3 mt-7">{['아직 익숙하지 않아요','조금 해봤어요','자신 있게 할 수 있어요'].map((answer,index)=><button key={answer} onClick={()=>{play(400+index*80); if (step === questions.length - 1) setMode('level'); else setStep(step + 1);}} className="rounded-2xl border border-white/20 p-5 text-left hover:bg-white/15">{answer}</button>)}</div></>}</section>);
  if(mode==='level') return shell(<section><p className="text-[#8ab4f8]">출발점 찾는 중</p><h1 className="text-3xl font-black mt-4">나에게 맞는 출발점을 골라볼까요?</h1><div className="flex overflow-x-auto gap-5 py-8 snap-x">{levels.map((item,index)=><button key={item.name} onClick={()=>{setLevel(index);play(600)}} className={`min-w-[280px] snap-center rounded-[2rem] p-7 text-left border-2 transition ${level===index?'bg-[#4285f4] border-white scale-105 shadow-2xl':'bg-white/10 border-white/15'}`}><p className="text-sm">{index===0?'추천 단계':'선택 가능'}</p><h2 className="text-2xl font-black mt-3">{item.name}</h2><p className="text-white/80 mt-3">{item.text}</p><p className="mt-6 font-bold">예상 {item.weeks} · 주 3회 · 하루 30분</p></button>)}</div><button onClick={()=>{play();setMode('tone')}} className="rounded-2xl bg-[#34a853] px-8 py-4 font-bold">이 단계로 여정 만들기</button></section>);
  if(mode==='tone') return shell(<section><p className="text-[#8ab4f8]">플래너 준비 중</p><h1 className="text-3xl font-black mt-4">어떤 코치와 함께할까요?</h1><div className="grid md:grid-cols-3 gap-4 mt-8">{tones.map((item,index)=><button onClick={()=>{setTone(index);play(500)}} key={item.name} className={`rounded-[2rem] p-6 text-left border-2 ${tone===index?'bg-[#ea4335] border-white scale-105':'bg-white/10 border-white/15'}`}><h2 className="font-black text-xl">{item.name}</h2><p className="text-white/80 mt-4">“{item.line}”</p></button>)}</div><button onClick={()=>{play(700);setMode('loading')}} className="mt-8 rounded-2xl bg-[#fbbc05] text-[#202124] px-8 py-4 font-black">내 학습 플래너 준비하기</button></section>);
  if(mode==='loading') return shell(<section className="text-center pt-32"><h1 className="text-3xl font-black">당신만의 구글러 여정을 준비하고 있어요.</h1><p className="text-[#8ab4f8] mt-8 animate-pulse">{messages[(Date.now()>>9)%messages.length]}</p><div className="mt-10 h-3 rounded-full bg-white/15 overflow-hidden"><div className="h-full w-4/5 bg-gradient-to-r from-[#4285f4] via-[#34a853] to-[#fbbc05] animate-pulse" /></div></section>);
  return shell(<section><p className="text-[#8ab4f8]">{tones[tone].name}의 첫 안내</p><h1 className="text-4xl font-black mt-3">{name||'구글러'}님의 Google 학습 플래너가 완성됐어요!</h1><p className="text-white/70 mt-3">{levels[level].name} · 목표: Google 도구를 자신 있게 활용하기 · 예상 완료 {levels[level].weeks}</p><div className="grid md:grid-cols-2 gap-5 mt-10"><div className="rounded-[2rem] bg-white text-[#202124] p-7"><h2 className="text-xl font-black">이번 주 학습 일정</h2>{['Google 계정 만들기','로그인과 로그아웃 연습','Gmail 메일 보내기','Drive 폴더 만들기','첫 주 복습 퀴즈'].map((item,index)=><button onClick={()=>setMode('legacy')} key={item} className="w-full text-left mt-3 rounded-xl bg-[#f1f3f4] p-4 hover:bg-[#e8f0fe]"><b>Day {index+1}</b> · {item}</button>)}</div><div className="rounded-[2rem] bg-[#1a73e8] p-7"><h2 className="font-black text-xl">오늘의 첫 미션</h2><p className="mt-4">{tones[tone].line}</p><p className="mt-6 text-white/75">학습 요일: 월·수·금<br/>하루 30분</p><button onClick={()=>setMode('legacy')} className="mt-8 rounded-xl bg-white text-[#1a73e8] px-5 py-3 font-bold">기존 학습 공간으로 가기</button></div></div></section>);
}
